import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '../components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/assets/images/icon.png" />
      <body className='bg-pattern'>
        <header className='mx-auto pt-2 pb-2'>
          
        </header>
        <div className='min-h-[73vh]'>
          {children}
          
        </div>
        <Footer />
      </body>
    </html>
  )
}
